---
title: "Confirmatory Data Analysis"
author: "SU Bo-Han"
date: "March 6, 2026"
date-modified: "last-modified"
format: 
  html:
    theme: cosmo  
---

## **1. Installing and launching required R packages**

```{r}
pacman::p_load(tidyverse, ggstatsplot)
```

## **2. Loading the data**

```{r}
#| message: false
#| warning: false
df <- read_csv("data/colombia_customers_processed.csv")
```

```{r}
ggbetweenstats(
  data = df,
  x = education_level,
  y = customer_lifetime_value,
  type = "nonparametric" 
)
```

```{r}
#| message: false
#| warning: false
#| fig-width: 8
#| fig-height: 6
ggbetweenstats(
  data = df,
  x = household_size,  
  y = customer_lifetime_value,
  type = "nonparametric",
  package = "ggthemes", 
  palette = "Tableau_20"
) +
  scale_y_log10() 
```

```{r}
#| message: false
#| warning: false
data_cleaned <- df %>%
  mutate(household_grp = case_when(
    household_size <= 2 ~ "Small (1-2)",
    household_size <= 4 ~ "Medium (3-4)",
    TRUE                ~ "Large (5+)"
  )) %>%
  mutate(household_grp = factor(household_grp, 
                                levels = c("Small (1-2)", "Medium (3-4)", "Large (5+)")))
ggbetweenstats(
  data = data_cleaned,     
  x = household_grp, 
  y = customer_lifetime_value,
  type = "nonparametric", 
  plot.type = "boxviolin",
  package = "ggthemes",
  palette = "Tableau_10",
  title = "Household Size vs. Customer Lifetime Value (Binned)",
  messages = FALSE
) +
  scale_y_log10(labels = scales::comma) + 
  labs(
    x = "Household Size Group",
    y = "CLV (Log Scale)",
    subtitle = "Grouping helps to balance sample sizes and clarify trends"
  )
```
